models.py
from flask_sqlalchemy import SQLAlchemy
from flask_login import UserMixin

db = SQLAlchemy()


#Creating model table for our CRUD database
class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(100))
    name = db.Column(db.String(1000))

    def __init__(self, name, email, password):
        self.name = name
        self.email = email
        self.password = password

    def create(self):
        db.session.add(self)
        db.session.commit()

    def update(self, values):
        for key, value in values.items():
            setattr(self, key, value)
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()


class Tache(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    titre = db.Column(db.String(100), nullable=False)
    description = db.Column(db.String(200))
    date_echeance = db.Column(db.Date)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    user = db.relationship('User', backref=db.backref('taches', lazy=True))

    def __init__(self, titre, description, date_echeance, user_id):
        self.titre = titre
        self.description = description
        self.date_echeance = date_echeance
        self.user_id = user_id

    def create(self):
        db.session.add(self)
        db.session.commit()

    def update(self, values):
        for key, value in values.items():
            setattr(self, key, value)
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()

app.py
from flask import Flask
from flask_login import LoginManager   #c'est pour gérer la gestion de l'autentification et la session utilisateur
from models import db, User
from routes import *                  # c'est pour definir les routes de notre page

app = Flask(__name__)
app.secret_key = "3d6f45a5fc12445dbac2f59c3b6c7cb1"          # c'est pour securiser les sessions utilisations et les cookies
 #Configuration de la base de données SqlAlchemy avec Postgres
app.config['SQLALCHEMY_DATABASE_URI'] = 'postgresql://flask:flask@localhost/crud'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db.init_app(app)  # c'est pour intialiser une extension

with app.app_context():
    db.create_all()    #permet de créer toutes les tables définies dans le modèle de base de données .

app.register_blueprint(user_bp)   # permet d'enregistrer un objet Blueprint dans une application Flask.

app.register_blueprint(tache_bp)

login_manager = LoginManager()
login_manager.login_view = 'user.login'
login_manager.init_app(app)

@login_manager.user_loader
def load_user(user_id):
    # since the user_id is just the primary key of our user table, use it in the query for the user
    return User.query.get(int(user_id))

if __name__ == "__main__":
    app.run(host='0.0.0.0', debug=True)

routes.py
from flask import Blueprint, render_template, request, redirect, flash, url_for
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, logout_user, current_user
from models import *


user_bp = Blueprint('user', __name__)

@user_bp.route('/profile')
@login_required
def profile():
    return render_template('profile.html', name=current_user.name)

@user_bp.route('/')
def login():
    return render_template("login.html")

@user_bp.route('/login', methods=['POST'])
def login_post():
    email = request.form.get('email')
    password = request.form.get('password')
#    remember = True if request.form.get('remember') else False

    user = User.query.filter_by(email=email).first()

    # check if the user actually exists
    # take the user-supplied password, hash it, and compare it to the hashed password in the database
    if not user or not check_password_hash(user.password, password):
        flash('Veuillez vérifier vos informations de connexion et réessayer.')
        return redirect(url_for('user.login'))  # if the user doesn't exist or password is wrong, reload the page

    # if the above check passes, then we know the user has the right credentials
    login_user(user)
    return redirect(url_for('tache.index'))

@user_bp.route('/signup')
def signup():
    return render_template("signup.html")

@user_bp.route('/signup', methods=['POST'])
def signup_post():
    email = request.form.get('email')
    name = request.form.get('name')
    password = request.form.get('password')

    user = User.query.filter_by(email=email).first()  # if this returns a user, then the email already exists in db

    if user:  # if a user is found, we want to redirect back to signup page so user can try again
        flash('l adresse mail existe déjà')
        return redirect(url_for('user.signup'))

    # create a new user with the form data. Hash the password so the plaintext version isn't saved.
    new_user = User(email=email, name=name, password=generate_password_hash(password, method='sha256'))

    # add the new user to the database
    new_user.create()

    return redirect(url_for('user.login'))

@user_bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('user.login'))

tache_bp = Blueprint('tache', __name__)

#This is the index route where we are going to
#query on all our employee data
@tache_bp.route('/index')
@login_required
def index():
    taches = Tache.query.filter_by(user_id=current_user.id).all()
    return render_template("index.html", user=current_user, taches=taches)

#this route is for inserting data to postgres database via html forms
@tache_bp.route('/insert', methods = ['POST'])
@login_required
def insert():
    if request.method == 'POST':
        titre = request.form['titre']
        description = request.form['description']
        date_echeance = request.form['date_echeance']
        user_id = current_user.id
        nouvelle_tache = Tache(titre, description, date_echeance, user_id)
        nouvelle_tache.create()
        flash("Vous avez créé une tache avec succés")
        return redirect(url_for('tache.index'))

#this is our update route where we are going to update our task
@tache_bp.route('/update', methods = ['GET', 'POST'])
@login_required
def update():
    if request.method == 'POST':
        tache_modifie = Tache.query.get(request.form.get('id'))
        tache_modifie.update(request.form)
        flash("Tache modifiée avec succes")
        return redirect(url_for('tache.index'))

#This route is for deleting our employee
@tache_bp.route('/delete/<id>/', methods = ['GET', 'POST'])
@login_required
def delete(id):
    tache_a_supprime = Tache.query.get(id)
    tache_a_supprime.delete()
    flash("Tache supprimée")
    return redirect(url_for('tache.index'))

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css')}}">
    <meta charset="UTF-8">
    <title>{% block title %}  {% endblock %}</title>
</head>
<body>

{% block body %} {% endblock %}




<script src="{{url_for('static', filename='js/jquery.slim.min.js')}}"></script>
<script src="{{url_for('static', filename='js/bootstrap.min.js')}}"></script>
<script src="{{url_for('static', filename='js/popper.min.js')}}"></script>

</body>
</html>

templates/header.html
{% extends 'base.html' %}



{% block title %} Flask CRUD {% endblock %}



{% block body %}

<div class="jumbotron p-3">
    <div class="well text-center">

        <h1>Gestionnaire des taches </h1>

    </div>


</div>


{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% include 'header.html' %}



{% block title %} Home {% endblock %}



{% block body %}

<div class="container">
    <div class="row">
        <div class="col md-12">
            <div class="jumbotron p-3">
                <a href="{{ url_for('user.logout') }}" type="button"  class="btn btn-danger navbar-item">
                Se deconnecter
                </a>
                <h2>Gestion de vos <b>Taches</b>  <button type="button"  class="btn btn-success float-right"
                data-toggle="modal" data-target="#mymodal">Ajouter une nouvelle tache</button> </h2>
                {% with messages = get_flashed_messages() %}
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-success alert-dismissable" role="alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="close">
                                    <span aria-hidden="true">x</span>
                                </button>
                                {{message}}
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
                <table class="table table-hover table-dark">
                    <tr>
                        <th>ID</th>
                        <th>Titre</th>
                        <th>Description</th>
                        <th>Date Echéance</th>
                    </tr>
                   {% for row in taches %}
                    <tr>
                        <td>{{row.id}}</td>
                        <td>{{row.titre}}</td>
                        <td>{{row.description}}</td>
                        <td>{{row.date_echeance}}</td>
                        <td>
                            <a href="/update/{{row.id}}" class="btn btn-warning btn-xs" data-toggle="modal" data-target="#modaledit{{row.id}}">Modifier</a>
                            <a href="/delete/{{row.id}}" class="btn btn-danger btn-xs" onclick="return confirm('Are You Sure To Delete ?')">Supprimer</a>
                        </td>
                    </tr>
                  <!-- Modal Edit Task-->
                    <div id="modaledit{{row.id}}" class="modal fade" role="dialog">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h4 class="modal-title">Modification de la tache</h4>
                                </div>
                                <div class="modal-body">
                                    <form action="{{url_for('tache.update')}}" method="POST">
                                        <div class="form-group">
                                            <label>Titre:</label>
                                            <input type="hidden"  name="id" value="{{row.id}}">
                                            <input type="text" class="form-control" name="titre" value="{{row.titre}}">
                                        </div>
                                        <div class="form-group">
                                            <label>Description</label>
                                            <input type="text" class="form-control" name="description" value="{{row.description}}">
                                        </div>
                                        <div class="form-group">
                                            <label>Date Echéance:</label>
                                            <input type="date" class="form-control" name="date_echeance" value="{{row.date_echeance}}">
                                        </div>
                                        <div class="form-group">
                                            <button class="btn btn-primary" type="submit">Modifier</button>
                                        </div>
                                    </form>
                                </div>
                                <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
                            </div>
                        </div>
                    </div>
                </div>
                    {% endfor %}
                </table>
            </div>
            <!-- Modal Add Taches-->
            <div id="mymodal" class="modal fade" role="dialog">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title">Ajouter une tache</h4>
                        </div>
                        <div class="modal-body">
                            <form action="{{url_for('tache.insert')}}" method="POST">
                                <div class="form-group">
                                    <label>Titre:</label>
                                    <input type="text" class="form-control" name="titre" required="1">
                                </div>
                                <div class="form-group">
                                    <label>Description:</label>
                                    <input type="description" class="form-control" name="description" required="0">
                                </div>
                                <div class="form-group">
                                    <label>Date Echeance</label>
                                    <input type="date" class="form-control" name="date_echeance">
                                </div>
                                <div class="form-group">
                                    <button class="btn btn-primary" type="submit">Ajouter une tache</button>
                                </div>
                            </form>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

templates/login.html
{% extends "base.html" %}
{% block title %} Login {% endblock %}
{% block body %}
<body>
    <!-- Backgrounds -->
    <div id="login-bg" class="container-fluid">
        <div class="bg-img"></div>
        <div class="bg-color"></div>
    </div>
    <!-- End Backgrounds -->

    <div class="container" id="login">
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <div class="login">
                    <h1>Connexion</h1>

                    <!-- Loging form -->
                    <form method="POST" action="/login">
                        {% with messages = get_flashed_messages() %}
                            {% if messages %}
                                <div class="alert alert-danger">
                                    {{ messages[0] }}
                                </div>
                            {% endif %}
                        {% endwith %}
                        <div class="form-group">
                            <input type="email" class="form-control" name="email"  aria-describedby="emailHelp" placeholder="Entrer votre email">
                        </div>
                        <div class="form-group">
                            <input type="password" class="form-control" name="password"  placeholder="Password">
                        </div>
                        <div class="form-check">
                            <label class="forgot-password"><a href="{{ url_for('user.signup') }}">Inscription</a></label>
                        </div>
                        <br>
                        <button type="submit" class="btn btn-lg btn-block btn-success">Se connecter</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</body>
{% endblock %}

templates/profile.html
{% extends "base.html" %}

{% block body %}
<h1 class="title">
  Welcome, {{ name }}!
</h1>
{% endblock %}

templates/signup.html
{% extends "base.html" %}

{% block body %}
<body>
    <!-- Backgrounds -->
    <div id="login-bg" class="container-fluid">
        <div class="bg-img"></div>
        <div class="bg-color"></div>
    </div>
    <!-- End Backgrounds -->

    <div class="container" id="login">
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <div class="login">
                    <h1>Inscription</h1>

                    <div class="card">
                        {% with messages = get_flashed_messages() %}
                            {% if messages %}
                                <div class="alert alert-danger">
                                    {{ messages[0] }}. Aller à la <a href="{{ url_for('user.login') }}">page de connexion</a>.
                                </div>
                            {% endif %}
                        {% endwith %}
                        <form method="POST" action="/signup">
                            <div class="form-group">
                                <input type="email" class="form-control" name="email" placeholder="Email" autofocus>
                            </div>
                            <div class="form-group">
                                <input type="text" class="form-control" name="name" placeholder="Nom" autofocus>
                            </div>
                            <div class="form-group">
                                <input type="password" class="form-control" name="password" placeholder="Mot de passe">
                            </div>
                            <div class="form-check">
                            <label class="forgot-password"><a href="{{ url_for('user.login') }}">Connexion</a></label>
                        </div>
                            <br>
                            <button type="submit" class="btn btn-lg btn-block btn-info">Inscription</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
{% endblock %}